language: java
jdk:
- oraclejdk8

notifications:
  slack:
    rooms:
      secure: F+o9FPgJxD6KnpcvCGm2VgvY72aCo/+RwBoIZoArB68L41rgiOUoKbqkH3Y1vLaqw6isyqa6dkuBKyFoKVwyjuDYn7Iaw2z86WZWRCB4SkqcAnVWQCUGZVPrFh38hUl++gUEYbzIPDLm8RgKOJr/9XBZaMoATJlmoenI9ZMuncI=
sudo: false

# TODO determine what these should be for Gradle 4.x
cache:
  directories:
    - $HOME/.gradle/wrapper/dists/gradle-2.6-bin
    - $HOME/.gradle/caches/modules-2/files-2.1

# TODO enable this once Travis builds the console
#deploy:
#  provider: script
#  script: resources/docker-hub/deploy-to-docker-hub.sh
#  on:
#    tags: true