resourceserver:
  build: shim-server/docker
  environment:
    SPRING_PROFILES_ACTIVE: development
  links:
    - mongo:mongo
  env_file:
    - resource-server.env
  ports:
    - "8084:8083"

mongo:
  image: mongo

console:
  build: shim-server-ui/docker
  ports:
    - "8083:8083"
  links:
    - resourceserver:resource-server
